name: app10aprendaingles
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  audioplayers: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #IMAGES
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/5.png
    - assets/images/6.png
    - assets/images/cao.png
    - assets/images/gato.png
    - assets/images/leao.png
    - assets/images/macaco.png
    - assets/images/ovelha.png
    - assets/images/vaca.png
    - assets/images/a.png
    - assets/images/e.png
    - assets/images/i.png
    - assets/images/o.png
    - assets/images/u.png
    #AUDIOS
    - assets/audios/1.mp3
    - assets/audios/2.mp3
    - assets/audios/3.mp3
    - assets/audios/4.mp3
    - assets/audios/5.mp3
    - assets/audios/6.mp3
    - assets/audios/cao.mp3
    - assets/audios/gato.mp3
    - assets/audios/leao.mp3
    - assets/audios/macaco.mp3
    - assets/audios/ovelha.mp3
    - assets/audios/vaca.mp3
    - assets/audios/a.mp3
    - assets/audios/e.mp3
    - assets/audios/i.mp3
    - assets/audios/o.mp3
    - assets/audios/u.mp3

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
